[[constraint]]
  name = "github.com/Jeffail/gabs"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  name = "github.com/imdario/mergo"
  version = "0.3.2"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/cobra"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  name = "goji.io"
  version = "2.0.0"

[[constraint]]
  name = "gopkg.in/h2non/gock.v1"
  version = "1.0.7"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.1.1"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.9.0"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.9.3"

[[override]]
  name = "k8s.io/client-go"
  version = "6.0.0"

[[constraint]]
  name = "github.com/spotahome/redis-operator"
  version = "0.2.0"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/go-multierror"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.2"
