ingress: daemon.nais.example.no
fasitUrl: https://fasit.example.no
clusterSubdomain: nais-example.nais.example.no
clusterName: kubernetes
istioEnabled: false
repository: navikt/naisd
minReplicas: 2
maxReplicas: 4
targetCPUUtilizationPercentage: 50
request:
  memory: 64Mi
  cpu: 250m
limit:
  memory: 128Mi
  cpu: 500m
vaultEnabled: false
vaultAddr: https://vault.example.com
vaultKVPath: /kv/kubernetes/env/zone
vaultAuthPath: /kubernetes/env/zone
vaultInitContainerImage: navikt/vks:25

version: 287.0.0
