fasitUrl: https://fasit.example.no
clusterSubdomain: nais-example.nais.example.no
clusterName: kubernetes
repository: navikt/naisd
minReplicas: 2
maxReplicas: 4
targetCPUUtilizationPercentage: 50
request:
  memory: 64Mi
  cpu: 250m
limit:
  memory: 128Mi
  cpu: 500m
version: 162.0.0
